travis:
  secure:
    BINSTAR_TOKEN: P13DFF8CudAFP45tVKakNp5+5aKUZy1+lrfdPveSAf1JrkpoXkvyhNiXv7qgLUuuJLGKjrKeuv2+XcDWSbm4fC5/UfSfySD9aejK1UoGu7XaNldRrx9PN7i+D6VxNxbTa7Sn4gRaOOKj9R0vCFcHo28hProEwj5WIqNnq9gg/DRKjSbbW3jzKY4dmbkKcW2UcRsKGhkC9mRpRmHDOh+xJAY9u/oa+bYYjANXCsqcUM1nHlKps0DT5fao6lhf+MvGGcpDxpC1ZEQrSccrnWHhjCumxkqYEugUaSH+cSe78C66bIITDEXXUrv4YxWpttKemXTiUFkXimPzXqtlhfEv8sg0g5YjL7FAis8fx8uTG161v3nNqR2Hk3nYl31d4jJfvOBpfbalK2WIpES4frkQ82r+VYUhidQhbNZSznhC6W2ipy5bA6LocUE8S6ETaExcWXF1Wl5NkHT/AUr+Q3djIpKDkA2JKqYpCOSyJJbbkv10UsrWbp42SVn/op13qLEXRh+H44WDIWpg6+78Gab2ota1lRuRBePLwWLKISsqXPkeztevXYkIp29FyBQGLghNfq7mqfL/ezPh68I2ZdY8GMgFveoHJ3a1cecrvNLNMfFQvq2awLBfXW/awSMt3fIrohk96DEm1Rf0bb0GOv69Q1rKD3qjQeIIhxW6Yb0kGOs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
