travis:
  secure:
    BINSTAR_TOKEN: IGUTxQKSVJPY6XVLymDuR4lhBGfpeph6bd7f40Lqer2SUacJCwX5cV6p2G4GW/RW4eScJRjGA+cDWYuAAt3kOeOvw3+j/FOmw65I9lwC5S9v40qtA5UNdTiMgqYypB01N1P8wvEzAYiFEMVl8jQCg3iWP97t4ccxFggBvyVo7t2+9hInKNjARg0ImblA8YyYwIN9IBprmTdAmjGM/Od/JNnMpKtxc19t8GUNs4Ju1OMrbMzAiem9RPzCOl8UFeU4jqYtS3G7KCXgdfKVWJAVlNyn41ov3xGkqqCC9clVce8nQLwpcmazA5FZvhRJ0Yr1Om2lRhnLZVqDvSaFVk8QRm+AQY8yn22VTpQNeTu9qkvC3+mi45BJfV3wDs3e2UiCcxxkJgPJ+sPG9NkJafKg2Nhsd9AHv36WfQp8yMJkkqJlpEw7tQeuj9e3utHg94a6CfaNEIXLuyU5Avegm2esIcGmrDyq2LOE0MNYCiIYXANQpQgnxQzAUrPFWxkKRHzb2+JG9kCshM9C2pdiiTBtMFZn3zTPIjQ6/QD96A0s1PbKWzhdl3m1MK37JYEx1/SWy7Zbr0z33XGhTENzNulPRUXgtnqYTLJ9FQ809ego/gOW1+I+qtkhe4CoRL71svd6l/9nvKdOpRslse8CQIw0Ty8DktFRHatUA/rWMcUwmzU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
