appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: SEfRQN2Pr73FGy0hyNPeVjjG0t3UQUQxIdGynty28ybl65OvBDzRQDblDljyvgp1rNA1RzgaSG79q0qlCFzFEFCpwBpNQORBEJL5f94N7OyU8cgannrDXxUXFEibbsVxfzwDT+ppkCL99xQU7ctelNIPocqd9UfbaXYs5QLn3u3q//hdmos5YOvEFCsbVllJc697scQqMdfBKJmcSs0zHGFX2Sv2LCaqM4rsvNq/LROcBFmApN8HIlpYBLFfqt2SDai2y6WVKPMA9ulPoYluBvUSGDGcGEsOdz4Y5vrh5ffWMaq8lphmwZZfuenYx6dbeuOT/vtzFidYzAkk8J4yh0e/kuYQ9RnxemcDf0NwvMUpL0NGK/9QCL1X5VYs7dHQBy1qGEfcU3tYhm5+ziC32TJbn4oz/MbWS4iooag3ixnc6wstbRKIz2IZ1SG+bcgFwk/KfuNY0ZE4JIhDrz1uur3srzk0miMJ6iK92oRw5uxTzhx+/iHmZe25fhnC1e9N0RMaU8qa6hI3u4Fyq1LC6+8gGbGtIxQrADurOyhYn6KlVaF3fOFo1nWY/4JTjnUiG7+JvgxrWvdOIC1eRZXlfT4y6t9WEayhCoKhPPKsdv/hfVkJuPD7WMciW9a9WG2vh4k9UqoKZ1OK+9jLiFLMarzqGF9MkJLqjgl/3A19Dzc=}
