travis:
  secure:
    BINSTAR_TOKEN: N2k8HvfYFrWCXbtgb1mI2FOMtYGPH1ZsLia0GyNbnM/MRztm/sDrZDj2PQZm1zsOjK9djTZoPmWncc5h1LpzPoz0AGSnmtf2Ng35A3HotCV4D4ta1mnyjig4xGCHrHkOyvwf1GxByM/eXhJA1aSwVNkFlARyKmL2TcJNNALm7rfwHQMPOg1ZTEIlda077eabnhx7brITKsXhYDLpPSFYekEKW9Cc6OUHRD8DkJ11hs1ktRL6pw8eb2mLn5+IpoJeAKW+8bPnjABbl4pQNOeD24uQILd2+E6tpDWmSqrtShCac/ZU8TxM0htLo8dEsPgvboa224CL/IGzSJ9eH/MsL8btE7uWmYRv2DfOp1OkwqXd9e007A2P+NYmCJDUhkLleLYGYB60EVVgYMthTmkQvS4gHxWI1w2ND66ITezuRTLVpskFOxjhVeuQeAnFhiHG+8C8xR81Y5yJFY+e7SuV6FUArPKrcvboKYIg3MjOYZB7/Wx6rDPR5EdIREbcVSFaf55vFNnwqp1JptAojp+8vaTzdWtkjUXpWjbypGqYPEjzdAiMiL2MMWzD3aKwrcut1s0kYtsWBK1+x0SfC7KX5zpumzSQScujxjd7kqEV4jZ5p56syrG/hjqhfOpksM8Y4Wj+/rRzxn38ezBVbz/tZq7S1zOibXKe73PUA0/Ktus=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
