travis:
  secure:
    BINSTAR_TOKEN: rdv6pVT8/2bPU1O8R+4GVqmcVzxesCSPXkj9KTHhWOQ7iSNTubQ8DrqofkPbWob6fEO3/Ht/9NwbR2aeugs1PjDmk5wSCiiXOZsUpKO1vG4o3WBxieTFbqNW08gQPxOg1TNyjpfuUwgNUeBymxWtevWdCfWP984OtHFmL6SFQEpMUKtCsRlEJFOcPbEvSsTQjGRaMzvL1nqK7Ttktl8dmiRbpcJasFnyjB18GFMp5LsgG/9emCoVqQYDnegO2xsp7/AKvHalrt9rs/KOjwnKKllVW2UZ/v0ZymnLd/1af0LZk1vpJ0jj/l5iIBwdHXrAyPq0+CGXT0xwsqjZTmLjQGH6XDoQCvksiwmJea6yAA5RRI6LNRgP90MzXBgJAT/wgyuNz2siUFUCUnxQOabU4cvNRR7P4pN/vUyUuQ7AUgFhqn+XvGiZpYHF2MwxLnF2UJyBJThHCl+mOnnrj/i43J70EeEcwdxSl+9MtGaIt2zpeNFVb36+XVfQcusbIEzf7FVZZ45zEhdMbVS6ouP1bvHys+RrVj0PgWa260JloOnnJ4+baYgIrqozhUGTYj7QipHBBNKa8oQrhNqAZc3pKjQZzL/3S1OsL/cUEpssQuhKDwrxYixgN8pmqRkndaYKAtd00SBXdqFU4svG8im+6rr60mzw9EWmv/IM8D/+j5s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
